apiVersion: v1
kind: Pod
metadata:
  name: cirros-dc-web
  labels:
    name: cirros-dc-web
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "default", "name":"dc-web-network"}'
  }
spec:
  containers:
  - name: cirros-dc-web
    image: cirros
    ports:
      - containerPort: 22
