apiVersion: v1
kind: Pod
metadata:
  name: cirros-mgmt
  labels:
    name: cirros-mgmt
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "default", "name":"mgmt-network"}'
  }
spec:
  containers:
  - name: cirros-mgmt
    image: cirros
    ports:
      - containerPort: 22
