apiVersion: v1
kind: ReplicationController
metadata:
  name: cirros-rc
spec:
  replicas: 2
  selector:
    app: cirros-rc
  template:
    metadata:
      name: cirros-rc
      labels:
        app: cirros-rc
    spec:
      containers:
      - name: cirros-rc
        image: cirros
        ports:
        - containerPort: 22
